name: 'Deploy to github pages'
on:
  push:
    branches:
      - master
jobs:
  Deploy-to-GitHub-Pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm install
    - name: Build static bundle
      run: |
        npm run build
        echo "votosphere.us.to" > CNAME
        touch .nojekyll
    - name: Push built artifacts
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
